### ISSUE TITLE
Adjust learning objectives

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/js-reference-types#24]
`Create and invoke functions with argument-dependent return values` should probably just be `Create and invoke functions`.

Argument-dependent return values are not covered, **or** I'm confused about what argument-dependent means. @gaand care to discuss?

**Comment by gaand** [comment]
Well, true functions always have argument dependent return values, but consider the following

```
const foo = function (first, second third) {
  return 12;
};
```

I showed them functions that have constant return values.

**Comment by gaand** [comment]
@jrhorn424 Is this still a thing?

**Comment by jrhorn424** [comment]
I don't think I made that point last time I taught this. In fact, I'm pretty sure I changed the objective on the fly when I wrote it on the board. I'm not opposed to leaving it in, or opposed to closing this issue, but I think it's a subtle point. I just wonder if it's something they need to take forward as fundamental understanding for other lessons.

**Comment by gaand** [comment]
So. if we moved the subtle part to the lesson and out of the objectives, would that improve things?

**Comment by jrhorn424** [comment]
@gaand I think so. The heuristic I have in mind is whether or not we desire to _diagnose_ the subtlety. If so, leave it in. If not, take it out and mention it in the lesson.

**Comment by gaand** [comment]
:robot: :speaking_head: Leave subtlety for possible discussion in the lesson.  As long as it doesn't disappear entirely, I'm fine with moving it to the lesson.
