### ISSUE TITLE
param vs arg

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/js-reference-types#28]
section about paramaters an arguments - @gaand

**Comment by gaand** [comment]
I think the formal parameters were named arg her, and therefore need to be changed.  I think this is my mistake (but I could be wrong).

**Comment by jrhorn424** [comment]
This is something we should all be consistent on. @gaand can you provide clarifications? Feel free to edit this comment. Also we have a space for this in the FAQ: https://github.com/ga-wdi-boston/meta/wiki/ArgsParamsVarsVals
- Parameters (also formal parameters) are named placeholders in function definitions
- Arguments (also bound parameters?) are values passed on function invocation

cc @ga-wdi-boston/core 

@payne-chris-r Mind making this change to this README?

**Comment by payne-chris-r** [comment]
Should I just remove the piece on formal and bound parameters? I feel like it's misleading and/or confusing. To me the point of this discussion is to define what are parameters and what are arguments... Would love your opinion @jrhorn424, @gaand, or @J-Weeks. Call the named placeholders in function definitions `parameters` and the values passed on function invocation `arguments`?

**Comment by jrhorn424** [comment]
> Call the named placeholders in function definitions parameters and the values passed on function invocation arguments?

Yes.

**Comment by payne-chris-r** [comment]
Addressed by a148972.

**Comment by payne-chris-r** [comment]
I actually think it was only kind of addressed by a148972. I'm pushing another fix that I think should put this to rest.

**Comment by payne-chris-r** [comment]
Ok to close @gaand ?

**Comment by RealWeeks** [comment]
@payne-chris-r add via merge @gaand

**Comment by gaand** [comment]
I think this is close enough.

@ga-wdi-boston/core We need to be consistent with this vocabulary.
