### ISSUE TITLE
Refactor lesson.

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/js-reference-types#29]
Lesson should be completely "refactored" to follow the: you do, I do, we do model - @gaand

**Comment by jrhorn424** [comment]
We should talk about this more. 'Nuke and pave' sounds more drastic than I think is intended. I'm ok with re-writing or re-scaffolding this, but I'd like input on the approach.

We've discussed this briefly in the past and I remember coming to the conclusion (maybe even convinced by @gaand) that some material is foundational and definitional. That conclusion may apply more strongly to js-basics than to this training, though.

**Comment by gaand** [comment]
The hyperbolic title came from the poetry of youth (so not from me :-).)

This comes from my sense of the room during this talk.

Some foundational material may not fit the following, but I think it should be used more during this sequence.

```
- demo
- code along
- lab
- repeat
```

**Comment by jrhorn424** [comment]
I don't think I planned far enough ahead to go through these sorts of changes with @payne-chris-r. Do you want to take this on your own, Chris? Lesson scaffolding can be fun, if intimidating.

**Comment by payne-chris-r** [comment]
Resolved with f4b0c08. Ok to close @J-Weeks ?

**Comment by jrhorn424** [comment]
I'm not sure this is resolved. See #17

**Comment by RealWeeks** [comment]
I'm going to cite and close this as I opened and it seems to be a dupe of #17 feel free to reopen for further discussion.
