### ISSUE TITLE
lab.js test tests against different paragraph text

### ISSUE THREAD

**Issue by sarabrentmccoy** [ga-wdi-boston/js-reference-types#3]
lab.js starts with "We the people..." text, but lab.spec.js test tests our code against the collections.js text ("When in the Course of human events...").

**Comment by gaand** [comment]
I don't understand why this is an issue.  Would you please elaborate?  Or perhaps we could chat about it?

**Comment by gaand** [comment]
This is an issue of arguments to functions over known variables.
