### ISSUE TITLE
Only name functions in expressions that require recursion.

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/js-reference-types#36]
I believe that was our conclusion in a long discussion issue somewhere, but I don't remember where.

So, change that in this repo, e.g.

``` diff
-const fullName = function fullName(given, family, east) {
+const fullName = function (given, family, east) {
   if (east) {
     return `${family} ${given}`;
   else {
     return `${given} ${family}`;
   }
 };
```

**Comment by RealWeeks** [comment]
I think we decided the opposite on this, @jrhorn424 changed it back if I remember correctly. I think the thinking was that we just show them and don't let them worry about understanding it.

That being said I'm 100% for the way this issue suggests. I think it's easier to developers to understand and makes more sense at this point.

**Comment by gaand** [comment]
See ga-wdi-boston/js-functions-ins-and-outs#15

@ga-wdi-boston/core My last comment there agrees with what I wrote here.

**Comment by RealWeeks** [comment]
Sorry it's tracked over a few issues, I'll change.

**Comment by gaand** [comment]
No need to apologize.  This is something we may need to track more globally.

@jrhorn424 Is that in instructors?  meta?  somewhere else?  I'm worried about not keeping up with non-repository tracked issues

**Comment by raq929** [comment]
Fixed e8b67728c94a7476d606c09de67122fac97ea35c.

**Comment by gaand** [comment]
It does not appear that that commit was merged.

**Comment by jrhorn424** [comment]
@gaand I see this as appropriate for `meta`. Do you agree? I'd like to know what keeps us from tracking things globally. I know there's a friction for me, but I can't identify it. Maybe the repos are poorly named? Maybe we just don't have that many global issues?

**Comment by jrhorn424** [comment]
@gaand This appears to be now merged.
