### ISSUE TITLE
update from node-template.

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/js-reference-types#37]
Why did I have to open this issue?

**Comment by RealWeeks** [comment]
I missed this.

**Comment by raq929** [comment]
It is now updated. dd9209d01811f170dcdf85bf568078e34f0a1d2d

**Comment by gaand** [comment]
It doesn't appear that this commit was merged to master.

**Comment by jrhorn424** [comment]
@gaand This appears to be now merged.
