### ISSUE TITLE
Corrected readme regression from 27eaa499807c0267d6328e79e2cbe33b6d99784d

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/js-reference-types#38]
Match parentheses:

``` diff
 ### Function information

--   [Function](https://en.wikipedia.org/wiki/Function_(mathematics)
+-   [Function](https://en.wikipedia.org/wiki/Function_(mathematics))
 -   [Subroutine](https://en.wikipedia.org/wiki/Subroutine)
 -   [Variable shadowing](http://en.wikipedia.org/wiki/Variable_shadowing)
--   [Parameter](https://en.wikipedia.org/wiki/Parameter_(computer_programming)
+-   [Parameter](https://en.wikipedia.org/wiki/Parameter_(computer_programming))

 ### Collection information

--   [List](https://en.wikipedia.org/wiki/List_(abstract_data_type)
+-   [List](https://en.wikipedia.org/wiki/List_(abstract_data_type))
 -   [Array](https://en.wikipedia.org/wiki/Array_data_structure)
 -   [Dictionary](https://en.wikipedia.org/wiki/Associative_array)
 -   [Hash](https://en.wikipedia.org/wiki/Hash_table)
```

**Comment by RealWeeks** [comment]
I did this because locally it causes linter errors. Also when using the markdown preview package it as having an added `)` at the end.

**Comment by jrhorn424** [comment]
What errors?

**Comment by jrhorn424** [comment]
The markdown preview package doesn't always work. I only use it for quick checks, not a canonical rendering. For that, you'll need to check out a local copy of, for example, `gollum` to get a github-correct rendering of the markdown file.

**Comment by RealWeeks** [comment]
I was too trusting :(

corrected in commit 2a5b6ca

**Comment by gaand** [comment]
@J-Weeks You broke process. Please don't do that.

**Comment by RealWeeks** [comment]
@gaand I know, this had a purpose. I couldn't see the changes using my preview so to make sure they look the same way I had to push. It was either create dummy repo or push here.

**Comment by gaand** [comment]
@J-Weeks Could you have checked on a fork?

**Comment by jrhorn424** [comment]
Is this closeable? @gaand
