### ISSUE TITLE
Delivery Question: Arguments object out of scope?

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/js-reference-types#41]
We discuss arguments and optional arguments. Is the lesson the one to introduce `arguments`?

**Comment by gaand** [comment]
Yes?  In passing? 

No?  Too soon?

 ins and outs covers it in some detail.

**Comment by jrhorn424** [comment]
I could be persuaded that it is too soon, but I think it does emphasize the point that parameters do not have to be named, and that JS doesn't check arity.

**Comment by jrhorn424** [comment]
@gaand Do you feel it is necessary for this talk?

**Comment by gaand** [comment]
I do not think it is necessary.  I'd guess it muddies the waters.

@jrhorn424 Please close if you concur.

**Comment by jrhorn424** [comment]
Thanks.
