### ISSUE TITLE
Question 3 of lib/lab.js is ambiguously worded.

### ISSUE THREAD

**Issue by joaufi** [ga-wdi-boston/js-reference-types#42]
Question: 
// 3. Write a function that returns the count of words in a string.
// Provid the _option_ to count unique words instead of total words.

The option part of question three says to count UNIQUE words instead of total words. That leads me to believe the amount of words that only appear once, so the count for a string of 'this a this' would be 1 as 'a' appears only once. Better phrasing for what is actually intended would be a count of all words not including repeating words, so the count of 'this a this' would be 2, as 'this' repeats twice and 'a' appears once.

(lib/collections.js has a similar ambiguity, which might be worth fixing as well)

**Comment by gaand** [comment]
An example in the instructions, as above, would help.
