### ISSUE TITLE
Poor solution line 34-40

### ISSUE THREAD

**Issue by neugierige** [ga-wdi-boston/js-reference-types#44]
1) The for-statement syntax is new to students, and they are using it wrong in their diagnostic.
2) The existence of both `uniqueWords` and `keys` seems completely redundant. Unless there is a mistake, and they are meant to be used differently?

```
// The keys pulled out into a list
let uniqueWords = [];

let keys = [];
let k = 0;
for (keys[k++] in uniqueWordsAsKeys); //jshint ignore:line

uniqueWords = keys;
```

**Comment by gaand** [comment]
If you are going to make judgments about the solutions ("Poor solution...") you should present an alternative you think is superior.  You should also ask about the purpose of solution branches before judging the code.  

The purpose of  `keys` seems obvious to me.  What about it do you find redundant?
