### ISSUE TITLE
Update readme to edit spec/lab.spec.js during the lab

### ISSUE THREAD

**Issue by bernardlee** [ga-wdi-boston/js-reference-types#50]
Line 16.
```javascript
xdescribe('collections lab', () => {
```
should be
```javascript
describe('collections lab', () => {
```

**Comment by gaand** [comment]
Incorrect. Please be sure something is wrong before opening an issue.

**Comment by bernardlee** [comment]
I misinterpreted the problem.  It's not a typo, but there should be an instruction in the readme to remove the x during the lab so that all of the tests run.

**Comment by gaand** [comment]
No, the point is to allow the other tests to be used without these tests failing.  Once they move into the lab, they should remove the leading `x`.

`grunt test` will show `xdescribe` tests as pending.

This issue should probably be about removing the `x` when starting the lab.

**Comment by bernardlee** [comment]
All right I didn't know how it worked and I'll update the issue title.

**Comment by gaand** [comment]
@bernardlee Thanks!
