### ISSUE TITLE
Should we re-order delivery?

### ISSUE THREAD

**Issue by MicFin** [ga-wdi-boston/js-reference-types#64]
Jumping from Reference Types and Assigment examples to Functions then to Arrays and Objects seems unintuitive to deliver.  I would suggest going from Reference Types and Assignments to Arrays and Objects and then Functions.

Currently the order of delivery is:
1.  [Reference Types / Assignment](https://github.com/ga-wdi-boston/js-reference-types#reference-types)
2.  [Functions](https://github.com/ga-wdi-boston/js-reference-types#demo-functions)
3.  [Collections (arrays/objects)](https://github.com/ga-wdi-boston/js-reference-types#collections)
4.  [Lab](https://github.com/ga-wdi-boston/js-reference-types#lab)

Recommended change to move Functions to before Lab.
1.  [Reference Types / Assignment](https://github.com/ga-wdi-boston/js-reference-types#reference-types)
2.  [Collections (arrays/objects)](https://github.com/ga-wdi-boston/js-reference-types#collections)
3.  [Functions](https://github.com/ga-wdi-boston/js-reference-types#demo-functions)
4.  [Lab](https://github.com/ga-wdi-boston/js-reference-types#lab)

**Comment by gaand** [comment]
The idea is to cover cover the larger cognitive load earlier.  So, functions are things people struggle to comprehend.

Your reordering puts the talk about functions just before using them in the lab.
